language: objective-c
xcode_workspace: ferriestimetable2.xcworkspace
osx_image: xcode7.2
script:
    - xctool build-tests -destination 'platform=iOS Simulator,name=iPhone 6' -workspace $WORKSPACE_NAME.xcworkspace -scheme $SCHEME_NAME
    - xctool run-tests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' -workspace $WORKSPACE_NAME.xcworkspace -scheme $SCHEME_NAME

env:
    global:
    - WORKSPACE_NAME="ferriestimetable2"
    - SCHEME_NAME="ferriestimetable2"