language: objective-c
xcode_project: ferriestimetable2.xcodeproj
script:
    - xcodebuild -workspace 'ferriestimetable2.xcworkspace'  -scheme ferriestimetable2 -destination "platform=iOS Simulator,name=iPhone 5,OS=8.0" test
